// tweet.interface.ts

export interface Tweet {
  id?: number; // Optional if using autogenerated IDs
  author: string;
  message: string;
  date: string; // Assuming date is a string in ISO format
}
